//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiosDeEntidadesFinancieras
    {
        public int BeneficioId { get; set; }
        public string DescripcionDeBeneficio { get; set; }
        public int EntidadFInancieraId { get; set; }
    
        public virtual EntidadesFinancieras EntidadesFinancieras { get; set; }
    }
}
