//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajesDeContacto
    {
        public string Nombre { get; set; }
        public decimal Telefono { get; set; }
        public string Empresa { get; set; }
        public string Correo { get; set; }
        public string Mensaje { get; set; }
        public int MensajeDeContactoId { get; set; }
    }
}
