//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesDeSuscripcion
    {
        public int PlanDeSuscripcion { get; set; }
        public decimal Precio { get; set; }
        public string Tipo { get; set; }
        public string TasasFinancieras { get; set; }
        public string Usuarios { get; set; }
        public int NumDescargas { get; set; }
        public bool TieneReportesMensuales { get; set; }
        public string UrlExterna { get; set; }
    }
}
