//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosFinancieros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosFinancieros()
        {
            this.CondicionesDeProductos = new HashSet<CondicionesDeProductos>();
            this.CostosRendimientosProductosFinancieros = new HashSet<CostosRendimientosProductosFinancieros>();
        }
    
        public int ProductoFinancieroId { get; set; }
        public string NombreProductoFianciero { get; set; }
        public int TipoDeOperacionId { get; set; }
        public string Icono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionesDeProductos> CondicionesDeProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostosRendimientosProductosFinancieros> CostosRendimientosProductosFinancieros { get; set; }
        public virtual TiposDeOperaciones TiposDeOperaciones { get; set; }
    }
}
