//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionEntidadesFinancierasRegiones
    {
        public int RelacionEntidadRegion { get; set; }
        public int EntidadFinancieraId { get; set; }
        public int RegionId { get; set; }
    
        public virtual Regiones Regiones { get; set; }
        public virtual EntidadesFinancieras EntidadesFinancieras { get; set; }
    }
}
